upstream catalog_service {
    server catalog-service:8000;
}

upstream venue_service {
    server venue-service:8001;
}

upstream user_service {
    server user-service:8002;
}

upstream inventory_service {
    server inventory-service:8003;
}

upstream booking_service {
    server booking-service:8006;
}

upstream payment_service {
    server payment-service:8007;
}

upstream notification_service {
    server notification-service:8008;
}
