# Gateway Health Status
location /health {
    access_log off;
    add_header Content-Type application/json;
    return 200 '{"status":"UP","gateway":"nginx-api-gateway"}';
}

# Upstream Services Health Status
location /health/user-service {
    access_log off;
    proxy_pass http://user_service/health;
}

location /health/catalog-service {
    access_log off;
    proxy_pass http://catalog_service/health;
}

location /health/venue-service {
    access_log off;
    proxy_pass http://venue_service/health;
}

location /health/inventory-service {
    access_log off;
    proxy_pass http://inventory_service/health;
}

location /health/booking-service {
    access_log off;
    proxy_pass http://booking_service/health;
}

location /health/payment-service {
    access_log off;
    proxy_pass http://payment_service/health;
}

location /health/notification-service {
    access_log off;
    proxy_pass http://notification_service/health;
}
