# Allocate 20MB of shared memory for tracking IPs (holds ~320k tracker states)
# Standard rate limit of 100 requests per second per IP

limit_req_zone $binary_remote_addr zone=gateway_limit:20m rate=100r/s;
