"""Initial schema

Revision ID: bf0657a30e85
Revises: None
Create Date: 2026-07-27 14:59:29.904595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf0657a30e85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('age_restriction', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='RUNNING', nullable=False),
    sa.Column('records_scraped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_normalized', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_imported', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('SCRAPER', 'PARTNER_JSON')", name='check_ingestion_source'),
    sa.CheckConstraint("status IN ('RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL')", name='check_ingestion_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('genre', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('trailer_url', sa.Text(), nullable=True),
    sa.Column('cast', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('crew', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ingestion_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rating IN ('U', 'UA', 'A', 'S')", name='check_movie_rating'),
    sa.CheckConstraint("source IN ('SCRAPED', 'MANUAL', 'PARTNER_API')", name='check_movie_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_movies_genre', 'movies', ['genre'], unique=False, postgresql_using='gin')
    op.create_index('idx_movies_language', 'movies', ['language'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_movies_release_date', 'movies', ['release_date'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_movies_slug', 'movies', ['slug'], unique=False)
    op.create_table('ingestion_dead_letter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('NORMALIZER', 'VALIDATOR', 'IMPORTER')", name='check_failed_record_stage'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_dead_letter')
    op.drop_index('idx_movies_slug', table_name='movies')
    op.drop_index('idx_movies_release_date', table_name='movies', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index('idx_movies_language', table_name='movies', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index('idx_movies_genre', table_name='movies', postgresql_using='gin')
    op.drop_table('movies')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
