"""initial_schema

Revision ID: 35769628c671
Revises: 
Create Date: 2026-07-28 15:13:07.896088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35769628c671'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('partner_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('screens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('screen_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("screen_type IN ('2D', '3D', 'IMAX', 'DOLBY', '4DX')", name='check_screen_type'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'name', name='uq_seat_types_screen_name')
    )
    op.create_table('showtimes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('catalog_ref_id', sa.UUID(), nullable=False),
    sa.Column('catalog_type', sa.String(), nullable=False),
    sa.Column('show_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('booking_open_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("catalog_type IN ('MOVIE', 'EVENT')", name='check_catalog_type'),
    sa.CheckConstraint("status IN ('SCHEDULED', 'OPEN', 'SOLD_OUT', 'CANCELLED', 'COMPLETED')", name='check_showtime_status'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'show_date', 'start_time', name='uq_showtimes_screen_slot')
    )
    op.create_table('seat_layout',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('seat_type_id', sa.UUID(), nullable=False),
    sa.Column('row_label', sa.String(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_type_id'], ['seat_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'seat_code', name='uq_seat_layout_screen_seat_code')
    )
    op.create_table('showtime_seat_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('showtime_id', sa.UUID(), nullable=False),
    sa.Column('seat_type_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['seat_type_id'], ['seat_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('showtime_id', 'seat_type_id', name='uq_showtime_seat_pricing')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtime_seat_pricing')
    op.drop_table('seat_layout')
    op.drop_table('showtimes')
    op.drop_table('seat_types')
    op.drop_table('screens')
    op.drop_table('venues')
    op.drop_table('cities')
    # ### end Alembic commands ###
