"""initial payment schema

Revision ID: f1fe5575a443
Revises: 
Create Date: 2026-08-03 10:36:01.256388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1fe5575a443'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=False),
    sa.Column('gateway_txn_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default='INR', nullable=False),
    sa.Column('status', sa.String(), server_default='INITIATED', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gateway IN ('MOCK_RAZORPAY', 'MOCK_STRIPE', 'MOCK_PAYU')", name='ck_payment_transactions_gateway'),
    sa.CheckConstraint("status IN ('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')", name='ck_payment_transactions_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_payment_booking_id', 'payment_transactions', ['booking_id'], unique=False)
    op.create_index('idx_payment_status', 'payment_transactions', ['status'], unique=False, postgresql_where=sa.text("status IN ('INITIATED', 'PENDING')"))
    op.create_index(op.f('ix_payment_transactions_booking_id'), 'payment_transactions', ['booking_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_txn_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSED', 'FAILED')", name='ck_refunds_status'),
    sa.ForeignKeyConstraint(['payment_txn_id'], ['payment_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payment_transactions_booking_id'), table_name='payment_transactions')
    op.drop_index('idx_payment_status', table_name='payment_transactions', postgresql_where=sa.text("status IN ('INITIATED', 'PENDING')"))
    op.drop_index('idx_payment_booking_id', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
